### ISSUE TITLE
Text box changed slightly after recent updates

### ISSUE THREAD

**Issue by LOuroboros** [JJMorton/discord-flat#1]
Title. The text box where you input your text looks different now than it did before, probably due to recent updates that the Discord Devs may have been pushing.
This is how it looks right now:
![firefox-2019-12-11_02-01-33](https://user-images.githubusercontent.com/4485172/70593009-501a7680-1bba-11ea-938e-8646f2624eb0.png)

The attachment button is misaligned, and so is the padding surrounding the text box, in my opinion.
Before, I remember the box using the entire rectangle where it is confined, something like this:
![firefox-2019-12-11_02-01-33](https://user-images.githubusercontent.com/4485172/70593253-10a05a00-1bbb-11ea-96a4-2f470a528336.png)

This CSS hasn't been worked on since 2018, so I don't know if you're willing to do anything about it @JJMorton, but I thought I should still submit an issue regardless, in case there's anybody else out there who uses this CSS just like me.

**Comment by JJMorton** [comment]
Thanks for opening an issue, not surprisingly almost the entire stylesheet was broken by discord updates over the past year or so.
I've pretty much just rewritten it, though I don't remember exactly what it looked like before so there's a good chance that there are differences. I've also left it very similar to the default style, though I think that's what it was like originally.

Dont hesitate to open any other issues if things break again :)
